[package]
name    = "forkit"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "forkit"
path = "src/main.rs"

[lib]
name    = "forkit"
path    = "src/lib.rs"

[[bench]]
name    = "perf"
harness = false

[dependencies]
sdl2  = { version = "0.37", features = ["ttf", "image", "mixer"] }
ureq  = { version = "2.10", features = [] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
